# Generated by Django 5.0.7 on 2024-08-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_change_category', 'Может изменять категорию продукта'), ('can_publish_product', 'Может публиковать продукт'), ('can_unpublish_product', 'Может отменять публикацию продукта')]},
        ),
    ]
