# Generated by Django 5.0.7 on 2024-07-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='published',
            new_name='is_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='preview',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='preview_image',
            field=models.ImageField(default='default.jpg', upload_to='blog_images/'),
        ),
    ]
